### PR TITLE
Fixes after Angular 9 migration and ag-grid and primeng updates

### LINKED ISSUE #383: Context Menu fails when option is a divider
**Describe the bug**
When we have a context menu with elements to separate blocks, the contextmenu fails

This problem is produced by a change in abstract-context-menu.component.ts, in the function getOption, where the actionId is undefined and we are trying to do a split.

### LINKED ISSUE #389: Favourites not working on Tree Combobox
**Describe the bug**
The favourite list is not saved on tree combobox.

**To Reproduce**
1. Go to a "tree-combobox"
2. Save one as favourite.
3. Close and return to the combobox
4. The favourites are not appearing.

**Expected behavior**
A list of selected favourites should appear at the top of the combo

### PR DESCRIPTION
**Pull request by carlosra85**
Fix #383
Fix #389 
Fix documentation links to redirect to lib
Fixes errors in ag-grid checkboxes in IE. Changes to use ag-grid checbox in cell renderers.
Fix null pointers in context menu
Improvement in context menu to restore scroll in single levels
Fix focus in datepicker
Fix spinner grid cell renderer not emitting change value
Fix grid rendering empty context menu while loading causing a flickering effect

### CODE REVIEW

File: projects/systelab-components/src/lib/combobox/renderer/combobox-favourite-renderer.component.ts [hunk 1]
```diff
@@ -1,28 +1,31 @@
...
 
 	public refresh(params: any): boolean {
 		return true;
 	}
 
-	private checkIfIsFavourite(): void {
-		this.isFavourite = this.favouriteList.map(String).indexOf(this.params.data[this.params.colDef.id].toString()) > -1;
+	private checkIfIsFavourite(params: any): void {
+		this.isFavourite = this.favouriteList.map(String)
+			.indexOf(params.data[params.colDef.id].toString()) > -1;
```
Comment (vinyulis) [inline projects/systelab-components/src/lib/combobox/renderer/combobox-favourite-renderer.component.ts:29]: use includes?
